name: workflow

on: [push, pull_request]

jobs:
    build:
        name: Build

        # https://github.com/mit-plv/fiat-crypto/pull/1971/files
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Set-up OCaml
              uses: ocaml/setup-ocaml@v3
              with:
                ocaml-compiler: 4
                dune-cache: true

            - run: opam install . --deps-only --with-test

            - run: eval $(opam env)

            - run: eval $(opam config env)

            - run: opam exec -- dune build

            - run: make test
